;;; -*- lexical-binding: t; -*-

(keymap-global-set "S-<down>" #'forward-paragraph)
(keymap-global-set "S-<up>" #'backward-paragraph)

(use-package puni
  :init
  (puni-global-mode))
(use-package meow
  :after (pretty-hydra)
  :config
  (defun my/meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

    (meow-motion-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("<escape>" . ignore))

    (meow-leader-define-key
     '("?" . meow-cheatsheet)
     '("/" . meow-keypad-describe-key)
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument))
    (meow-normal-define-key
     '("1" . meow-expand-1)
     '("2" . meow-expand-2)
     '("3" . meow-expand-3)
     '("4" . meow-expand-4)
     '("5" . meow-expand-5)
     '("6" . meow-expand-6)
     '("7" . meow-expand-7)
     '("8" . meow-expand-8)
     '("9" . meow-expand-9)
     '("0" . meow-expand-0)
     '("-" . negative-argument)
     ;; '("'" . repeat)
     ;;'("," . meow-inner-of-thing)
     ;;'("." . meow-bounds-of-thing)
		 '(":" . execute-extended-command)
		 '(";" . eval-expression)
     '("," . puni-mark-list-around-point)
	  '("." . puni-mark-sexp-around-point)
     '("RET" . command-palette/body)
	  '("TAB" . meta-navigation/body)
	  '("<escape>" . ignore)
	  '("a" . meow-append)
     ;'("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . puni-expand-region)
     '("G" . meow-grab) ;; ?
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     ;'("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     ;'("o" . meow-block)
     ;'("O" . meow-to-block)
     '("o" . meow-open-below)
     '("O" . meow-open-above)
     '("p" . meow-yank)
     '("q" . meow-goto-line)
     '("r" . meow-reverse)
     '("s" . meow-kill)
     '("S" . puni-transpose)
     '("t" . meow-till)
     '("u" . meow-undo)
     ;;'("w" . meow-mark-word)
     ;;'("W" . meow-mark-symbol)
     '("w" . puni-mark-sexp-at-point)
     '("x" . meow-line)
     '("y" . meow-save)
     ; '("z" . meow-pop-selection)
))
  (my/meow-setup)
  (meow-global-mode 1)
  :custom
  (meow-use-clipboard t))

(provide 'init-edit)
