((majutsu-bookmark nil)
 (majutsu-dispatch nil)
 (majutsu-git-clone-transient
  ("--colocate" "--remote=origin")
  ("--colocate"))
 (majutsu-git-fetch-transient nil)
 (majutsu-git-push-transient nil
									  ("--bookmark=normalize_repository4")
									  ("--bookmark=normalize_repository3")
									  ("--bookmark=normalize_repository2")
									  ("--bookmark=normalize_repository1")
									  ("--bookmark=xtask_runner_definition")
									  ("--bookmark=main")
									  ("--remote=origin"))
 (majutsu-git-push:-b)
 (majutsu-git-remote-transient nil)
 (majutsu-git-transient nil)
 (majutsu-log nil)
 (majutsu-new nil)
 (majutsu-rebase
  ("--onto=rwuprlty")
  ("--onto=qnzkttsw")
  ("--onto=kurzuxpm")
  ("--onto=wmqvqusk")
  ("--onto=npwqsnyl"))
 (majutsu-split nil)
 (transient:majutsu-git-clone-transient:--remote= "origin")
 (transient:majutsu-git-push-transient:--remote= "origin"))
