((majutsu-bookmark nil)
 (majutsu-dispatch nil)
 (majutsu-git-clone-transient nil)
 (majutsu-git-push-transient nil)
 (majutsu-git-remote-transient nil)
 (majutsu-git-transient nil)
 (majutsu-log nil))
