{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.dotfiles.features.aiTools;
  emacsEnabled = config.dotfiles.programs.emacs.enable;
  anvilPackage = import ../../../../pkg/anvil.nix {
    inherit lib pkgs;
    emacsPackage = config.programs.emacs.package;
  };
in
{
  config = lib.mkIf (cfg.enable && emacsEnabled) {
    home.packages = [ anvilPackage ] ++ anvilPackage.runtimePackages;

    xdg.configFile."emacs/lisp/init-anvil.el".text = ''
      ;;; -*- lexical-binding: t; -*-
      ;; Generated by Home Manager.

      (add-to-list 'load-path "${anvilPackage}/share/anvil")
      (require 'anvil)

      ;; Keep the advertised MCP surface untrimmed.  The `manifest'
      ;; module is deliberately loaded last so it sees all registrations.
      (setenv "ANVIL_PROFILE" "full")
      (setq anvil-modes-allow-buffer-modify '(fundamental-mode))
      (setq anvil-pty-broker-allowed-commands
            '("bash" "sh" "nu" "codex" "claude" "aider" "gemini"))
      (setq anvil-memory-obs-enabled t)
      (setq anvil-optional-modules
            '(xlsx
              pdf
              cron
              sqlite
              elisp
              sexp
              org-index
              buffer
              dev
              offload
              browser
              state
              session
              compact
              http
              shell-filter
              context
              harness-telemetry
              orchestrator
              pty-broker
              defs
              bisect
              ide-treesit
              py
              ts
              js
              discovery
              disclosure
              sexp-cst
              lint
              memory
              memory-bridge
              memory-obs
              extend
              semantic
              autoresearch
              claude-watchdog
              manifest))

      (provide 'init-anvil)
    '';
  };
}
